# Generated by Django 4.2.1 on 2023-06-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_of_tickets',
            field=models.IntegerField(default=1),
        ),
    ]
