# Generated by Django 4.2.1 on 2023-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_purchase_amount_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='email',
            field=models.EmailField(default='qwerty@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cashier',
            name='phone_number',
            field=models.CharField(default='+375445574128', max_length=13),
        ),
        migrations.AddField(
            model_name='cashier',
            name='role',
            field=models.CharField(default='sell tickets', max_length=500),
        ),
    ]
