# Generated by Django 4.2.1 on 2023-09-10 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateField(default=datetime.date(2023, 9, 10))),
                ('title', models.CharField(default='New film', max_length=100)),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
    ]
