# Generated by Django 4.2.1 on 2023-09-12 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_news_publish_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='photos/news/news1', upload_to='photos/news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 20, 49, 42, 689130)),
        ),
    ]
