# Generated by Django 4.2.1 on 2023-09-12 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_news_photo_alter_news_publish_alter_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='photos/news/news1.jpeg', upload_to='photos/news'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 21, 1, 23, 275688)),
        ),
    ]
