# Generated by Django 4.2.1 on 2023-09-13 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_news_photo_alter_review_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='SALE5%', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateField(default=datetime.date(2023, 9, 13)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 8, 44, 26, 830098)),
        ),
    ]
