# Generated by Django 4.2.1 on 2023-09-13 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_salecode_alter_news_publish_alter_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bought_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 11, 38, 39, 398474), help_text='Date and time when ticket was bought'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 11, 38, 39, 397116)),
        ),
    ]
