# Generated by Django 4.2.1 on 2023-11-06 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_purchase_bought_at_alter_review_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateField(default=datetime.date(2023, 11, 6)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bought_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 11, 59, 0, 386240), help_text='Date and time when ticket was bought'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 11, 59, 0, 384850)),
        ),
    ]
